[supervisord]
nodaemon=true

[program:redis]
command=redis-server
autorestart=true

[program:app]
command=uv run uvicorn main:app --host 127.0.0.1 --port 8000
directory=/app
autorestart=true
startsecs=5
startretries=5

[program:worker]
command=uv run python run_worker.py worker.settings.WorkerSettings
directory=/app
autorestart=true
startsecs=5
startretries=5

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
