all:
  hosts:
    node-1:
      ansible_host: 192.168.1.105
      ansible_user: ekku
      ansible_port: 22
      ansible_python_interpreter: auto_silent
      ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      os_family: debian
      tags:
      - rpi4
      - 8gb
